package intTest;



pub fn add(x: Int, y: Int) -> Int {
   return x + y;
}

pub fn sub(x: Int, y: Int) -> Int {
   return x - y;
}

pub fn mul(x: Int, y: Int) -> Int {
   return x * y;
}

pub fn div(x: Int, y: Int) -> Int {
   return x / y;
}

pub fn mod(x: Int, y: Int) -> Int {
   return x % y;
}

pub fn neg(x: Int) -> Int {
   return -x;
}

pub fn compoundAssign(inout x: Int, y: Int) {
   x += y;
   x -= y;
   x *= y;
   x /= y;
   x %= y;
}